name: pagosB
services:

  graphqludea1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    networks:
      - my_bridge_network


networks:
  my_bridge_network:
    external: true