version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: paymentsB
    ports:
      - "5441:5441"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  graphqludea1:
    build: .
    ports:
      - "8009:8009"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paymentsB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  postgres-data:
